# Generated by Django 5.2.10 on 2026-03-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='ctreated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_status_changed', 'Order status changed'), ('product_status_changed', 'Product status changed')], max_length=70),
        ),
    ]
